icons_format = "{icon}"

[theme]
theme = "ctp-macchiato"

[icons]
icons = "material-nf"
 
[[block]]
block = "weather"
format = "$icon $temp F"
[block.service]
name = "openweathermap"
api_key = "3bc91626b32fdadc041d674e4027c2cd"
coordinates = ["36.1881546","-96.3325038"]
units = "imperial"
forecast_hours = 9

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
format = " $icon $utilization "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
format = " $icon $speed_down $speed_up {$signal_strength $ssid |Wired connection} $ip "

[[block]]
block = "battery"
format = " $icon $percentage "
missing_format = ""

[[block]]
block = "external_ip"
format = " $ip"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %m/%d/%Y %l:%H %p') "
